### ISSUE TITLE
can't create build

### ISSUE THREAD

**Issue by codeHatcher** [codeHatcher/bnog-physipad#31]
using branch release/0.0.1
switched to n version 7.8.0
npm version 4.2.0 as per docs

ran `npm i`, `npm link`, `npm run ios`

got the following error
![image](https://user-images.githubusercontent.com/5360982/31974393-7f29aa5c-b8f9-11e7-8627-3086ec01477c.png)

npm logfile attached
[2017-10-25T00_25_13_964Z-debug.log](https://github.com/codeHatcher/bnog-physipad/files/1412880/2017-10-25T00_25_13_964Z-debug.log)

**Comment by codeHatcher** [comment]
I was able to get this running by deleting my bnog-physipad directory and cloning again from the repo, not sure why that worked since I had a `git checkout --hard` which should have accomplished the same thing

**Comment by codeHatcher** [comment]
I was able to make an archive in xcode but ran into the following
![image](https://user-images.githubusercontent.com/5360982/31975431-37ae2026-b8ff-11e7-8f6d-26108593f617.png)

let's go ahead and use any default icons (we can change these later) but need to get this deployed to app store

**Comment by codeHatcher** [comment]
I was able to fix the ipad multitasking issue via https://github.com/codeHatcher/bnog-physipad/issues/32

**Comment by RostikMoroziuk** [comment]
Previously we have package `react-native-youtube`. In latest commit, I had removed it and maybe this package was linking but not installed in your project. That is why you had this error.
